[package]
name = "wasmdome_wascc"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "wasmdome_wascc"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
wascap = "0.4.7"
latticeclient = "0.0.1"